-- 1. Create the Tasks Table
CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    wheel_type TEXT NOT NULL, -- 'bossing', 'skilling', or 'other'
    default_enabled BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 3. Create a Policy to allow ANYONE to read the tasks
CREATE POLICY "Allow public read access" ON public.tasks FOR SELECT USING (true);

-- 4. Insert Bossing Tasks
INSERT INTO public.tasks (name, category, wheel_type, default_enabled) VALUES
('Abyssal Sire', 'Slayer Boss', 'bossing', true),
('Alchemical Hydra', 'Slayer Boss', 'bossing', true),
('Barrows Brothers', 'Minigame Boss', 'bossing', true),
('Bryophyta', 'Free-to-play Boss', 'bossing', false),
('Callisto / Artio', 'Wilderness Boss', 'bossing', false),
('Cerberus', 'Slayer Boss', 'bossing', true),
('Chambers of Xeric', 'Raid', 'bossing', true),
('Chaos Elemental', 'Wilderness Boss', 'bossing', false),
('Chaos Fanatic', 'Wilderness Boss', 'bossing', false),
('Commander Zilyana', 'God Wars', 'bossing', true),
('Corporeal Beast', 'Group Boss', 'bossing', true),
('Crazy Archaeologist', 'Wilderness Boss', 'bossing', false),
('Dagannoth Prime', 'Dagannoth Kings', 'bossing', true),
('Dagannoth Rex', 'Dagannoth Kings', 'bossing', true),
('Dagannoth Supreme', 'Dagannoth Kings', 'bossing', true),
('Deranged Archaeologist', 'Fossil Island Boss', 'bossing', false),
('Duke Sucellus', 'Desert Treasure II', 'bossing', true),
('General Graardor', 'God Wars', 'bossing', true),
('Giant Mole', 'Mid-level Boss', 'bossing', true),
('Grotesque Guardians', 'Slayer Boss', 'bossing', false),
('Hespori', 'Farming Boss', 'bossing', false),
('Kalphite Queen', 'Desert Boss', 'bossing', true),
('King Black Dragon', 'Wilderness Boss', 'bossing', true),
('Kraken', 'Slayer Boss', 'bossing', true),
('Kree''arra', 'God Wars', 'bossing', true),
('K''ril Tsutsaroth', 'God Wars', 'bossing', true),
('Leviathan', 'Desert Treasure II', 'bossing', true),
('Nex', 'God Wars', 'bossing', true),
('Nightmare / Phosani', 'Group Boss', 'bossing', true),
('Obor', 'Free-to-play Boss', 'bossing', false),
('Phantom Muspah', 'Quest Boss', 'bossing', true),
('Sarachnis', 'Mid-level Boss', 'bossing', true),
('Scorpia', 'Wilderness Boss', 'bossing', false),
('Scurrius', 'Mid-level Boss', 'bossing', false),
('Skotizo', 'Catacombs Boss', 'bossing', true),
('Spindel / Venenatis', 'Wilderness Boss', 'bossing', false),
('Tempoross', 'Skilling Boss', 'bossing', false),
('The Corrupted Gauntlet', 'Minigame Boss', 'bossing', true),
('The Gauntlet', 'Minigame Boss', 'bossing', false),
('The Whisperer', 'Desert Treasure II', 'bossing', true),
('Theatre of Blood', 'Raid', 'bossing', true),
('Thermonuclear Smoke Devil', 'Slayer Boss', 'bossing', true),
('Tombs of Amascut', 'Raid', 'bossing', true),
('TzKal-Zuk (Inferno)', 'Minigame Boss', 'bossing', true),
('TzTok-Jad (Fight Caves)', 'Minigame Boss', 'bossing', true),
('Vardorvis', 'Desert Treasure II', 'bossing', true),
('Vet''ion / Calvar''ion', 'Wilderness Boss', 'bossing', false),
('Vorkath', 'Quest Boss', 'bossing', true),
('Wintertodt', 'Skilling Boss', 'bossing', false),
('Zalcano', 'Skilling Boss', 'bossing', false),
('Zulrah', 'Solo Boss', 'bossing', true);

-- 5. Insert Skilling Tasks
INSERT INTO public.tasks (name, category, wheel_type, default_enabled) VALUES
('Agility - Rooftops', 'Active', 'skilling', true),
('Agility - Hallowed Sepulchre', 'Active', 'skilling', true),
('Agility - Prifddinas Course', 'Active', 'skilling', false),
('Construction - Mahogany Homes', 'Minigame', 'skilling', true),
('Construction - Mythical Capes', 'Active', 'skilling', false),
('Cooking - 1-Tick Karambwans', 'Active', 'skilling', false),
('Cooking - AFK Sharks/Mantas', 'AFK', 'skilling', true),
('Crafting - Glassblowing', 'AFK', 'skilling', true),
('Crafting - Dragonhide Bodies', 'Active', 'skilling', false),
('Farming - Herb Run', 'Passive', 'skilling', true),
('Farming - Tree Run', 'Passive', 'skilling', true),
('Farming - Tithe Farm', 'Minigame', 'skilling', false),
('Firemaking - Wintertodt', 'Minigame', 'skilling', true),
('Firemaking - Redwood Logs', 'AFK', 'skilling', false),
('Fishing - Barbarian Fishing', 'AFK', 'skilling', true),
('Fishing - Tempoross', 'Minigame', 'skilling', true),
('Fishing - Karambwans', 'AFK', 'skilling', true),
('Fletching - Dart Tips', 'Active', 'skilling', false),
('Fletching - Magic Longbows', 'AFK', 'skilling', true),
('Herblore - Making Potions', 'Active', 'skilling', true),
('Hunter - Birdhouse Run', 'Passive', 'skilling', true),
('Hunter - Herbiboar', 'Active', 'skilling', true),
('Hunter - Chinchompas', 'Active', 'skilling', true),
('Magic - High Alchemy', 'Active', 'skilling', true),
('Magic - Bursting/Barraging Monkeys', 'Active', 'skilling', false),
('Mining - Motherlode Mine', 'AFK', 'skilling', true),
('Mining - Volcanic Mine', 'Minigame', 'skilling', true),
('Mining - Amethyst', 'AFK', 'skilling', true),
('Mining - 3-Tick Granite', 'Active', 'skilling', false),
('Runecraft - Guardians of the Rift', 'Minigame', 'skilling', true),
('Runecraft - ZMI / Ourania', 'AFK', 'skilling', true),
('Runecraft - Blood Runes (Zeah)', 'AFK', 'skilling', true),
('Runecraft - True Blood Altar', 'Active', 'skilling', false),
('Smithing - Giants'' Foundry', 'Minigame', 'skilling', true),
('Smithing - Blast Furnace', 'Active', 'skilling', true),
('Smithing - Dart Tips', 'AFK', 'skilling', false),
('Thieving - Ardougne Knights', 'Active', 'skilling', true),
('Thieving - Pyramid Plunder', 'Minigame', 'skilling', true),
('Thieving - Stealing Artefacts', 'Active', 'skilling', false),
('Woodcutting - Forestry', 'AFK', 'skilling', true),
('Woodcutting - Sulliuscep Mushrooms', 'Active', 'skilling', false),
('Woodcutting - 2-Tick Teaks', 'Active', 'skilling', false);

-- 6. Insert Other Tasks (Diversions)
INSERT INTO public.tasks (name, category, wheel_type, default_enabled) VALUES
('Pest Control', 'Minigame', 'other', true),
('Barbarian Assault', 'Minigame', 'other', false),
('Soul Wars', 'Minigame', 'other', false),
('Castle Wars', 'Minigame', 'other', false),
('LMS (Last Man Standing)', 'PvP', 'other', false),
('Wilderness Rev Cave PK', 'PvP', 'other', false),
('Bounty Hunter', 'PvP', 'other', false),
('Mage Training Arena', 'Minigame', 'other', false),
('Trouble Brewing', 'Minigame', 'other', false),
('Easy Clue Scrolls', 'Clues', 'other', true),
('Medium Clue Scrolls', 'Clues', 'other', true),
('Hard Clue Scrolls', 'Clues', 'other', true),
('Elite Clue Scrolls', 'Clues', 'other', true),
('Master Clue Scrolls', 'Clues', 'other', true),
('Questing - Do 1 Quest', 'Progression', 'other', true),
('Achievement Diary - Do 1 Tier', 'Progression', 'other', true),
('Combat Achievements - Do 5 Tasks', 'Progression', 'other', true),
('Gnome Restaurant', 'Minigame', 'other', false),
('Mahogany Homes', 'Minigame', 'other', false),
('Temple Trekking', 'Minigame', 'other', false);
